apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  astonvilla-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://192.168.132.143:6443
  source:
    path: astonvilla-app # you chould provide the folder in the git repo
    repoURL: "https://github.com/salsabylHam/argocd.git" # the url of the github repository
    targetRevison: HEAD # the branch of the github repository.We can use Head or a specific version
  syncPolicy:
    automated: {} # This will detect changes automatically from the repository
    syncOptions:
      - CreateNamespace=true

